// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFYkmOoNIWzWSzdHgYBC9qLCC7s0vuRhI',
    appId: '1:90761896525:web:79e1702b3a4e81d11cb204',
    messagingSenderId: '90761896525',
    projectId: 'flutter-sign-in-530b5',
    authDomain: 'flutter-sign-in-530b5.firebaseapp.com',
    databaseURL: 'https://flutter-sign-in-530b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-sign-in-530b5.appspot.com',
    measurementId: 'G-463ZLZJV4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10EWlemSbNfMxOfrpUMnD221SoGfx8R8',
    appId: '1:90761896525:android:f890c8f6cd6f58f71cb204',
    messagingSenderId: '90761896525',
    projectId: 'flutter-sign-in-530b5',
    databaseURL: 'https://flutter-sign-in-530b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-sign-in-530b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJQb9rnUpQoP5UbiqC1iPOnMQmPlx_yaw',
    appId: '1:90761896525:ios:d0571f4acfce82141cb204',
    messagingSenderId: '90761896525',
    projectId: 'flutter-sign-in-530b5',
    databaseURL: 'https://flutter-sign-in-530b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-sign-in-530b5.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJQb9rnUpQoP5UbiqC1iPOnMQmPlx_yaw',
    appId: '1:90761896525:ios:59486b262a0970311cb204',
    messagingSenderId: '90761896525',
    projectId: 'flutter-sign-in-530b5',
    databaseURL: 'https://flutter-sign-in-530b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-sign-in-530b5.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
